package com.github.litesql.jdbc.driver.ha;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.util.LinkedHashMap;
import java.util.Map;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;

import com.dbeaver.jdbc.model.AbstractJdbcStatement;
import com.github.litesql.jdbc.driver.ha.client.HAExecutionResult;

public class HAStatement extends AbstractJdbcStatement<HAConnection> {

    protected String queryText;
    protected Map<Object, Object> parameters = new LinkedHashMap<>();

    protected HAExecutionResult executionResult;
    protected int updateCount;
    protected HAResultSet resultSet;
    
    protected int queryTimeout;

    public HAStatement(@NotNull HAConnection connection) throws SQLException {
        super(connection);
        this.queryTimeout = 60; // default timeout in seconds
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {    	
        executionResult = connection.getClient().executeQuery(sql, parameters, this.queryTimeout);
        return getResultSet();
    }

    @Override
    public ResultSet executeQuery() throws SQLException {
        return executeQuery(queryText);
    }

    @Override
    protected boolean execute(@NotNull String sql, @Nullable int[] columnIndexes, @Nullable String[] columnNames, int autoGeneratedKeys) throws SQLException {
    	executionResult = connection.getClient().execute(sql, parameters, this.queryTimeout);
        return true;
    }

    @Override
    public boolean execute() throws SQLException {
    	executionResult = connection.getClient().execute(queryText, parameters, this.queryTimeout);
        return true;
    }

    @Override
    protected int executeUpdate(@NotNull String sql, @Nullable int[] columnIndexes, @Nullable String[] columnNames, int autoGeneratedKeys) throws SQLException {
    	this.updateCount = connection.getClient().executeUpdate(sql, parameters, this.queryTimeout);
        return this.updateCount;
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
    	this.updateCount = connection.getClient().executeUpdate(sql, parameters, this.queryTimeout);
        return this.updateCount;
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
    	this.updateCount = connection.getClient().executeUpdate(sql, parameters, this.queryTimeout);
        return this.updateCount;
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    	this.updateCount = connection.getClient().executeUpdate(sql, parameters, this.queryTimeout);
        return this.updateCount;
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
    	this.updateCount = connection.getClient().executeUpdate(sql, parameters, this.queryTimeout);
        return this.updateCount;
    }

    @Override
    public long executeLargeUpdate() throws SQLException {
    	this.updateCount = connection.getClient().executeUpdate(queryText, parameters, this.queryTimeout);
        return this.updateCount;
    }

    @Override
    public void close() throws SQLException {
    }

    @Override
    public void cancel() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        if (resultSet == null) {
            if (executionResult == null) {
                throw new SQLException("No result set was returned from server");
            }
            resultSet = new HAResultSet(this, executionResult);
        }        
        return resultSet;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return (int) this.updateCount;
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        return this.updateCount;
    }

    @Override
	public int getQueryTimeout() throws SQLException {
		return this.queryTimeout;
	}

	@Override
	public void setQueryTimeout(int seconds) throws SQLException {
		this.queryTimeout = seconds;
	}

	@Override
    public boolean getMoreResults() throws SQLException {
        return false;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {

    }

    @Override
    public int getFetchDirection() throws SQLException {
        return ResultSet.FETCH_FORWARD;
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return false;
    }
    @Override
    public boolean isClosed() throws SQLException {
        return false;
    }

}
